version: '3.8'

services:
  shutdown-service:
    build: .
    container_name: pi-shutdown
    environment:
      - SHUTDOWN_TOKEN=supersecret
    ports:
      - "3000:3000"
    volumes:
      - /run/systemd:/run/systemd
      - /run/dbus:/run/dbus
      - /dev:/dev
    privileged: true
    restart: no
