version: '3.8'

services:
  shutdown-service:
    build: .
    container_name: pi-shutdown
    environment:
      - SHUTDOWN_TOKEN=supersecret   # Optional token
    ports:
      - "3000:3000"
    volumes:
      - /sbin/shutdown:/sbin/shutdown:ro   # Mount host shutdown command
    privileged: true                       # Required to run shutdown
    restart: no
