version: '3.8'
services:
  shutdown-service:
    build: .
    container_name: pi-shutdown
    ports:
      - "3000:3000"
    volumes:
      - /sbin/shutdown:/sbin/shutdown # bind host shutdown binary
    restart: no
    privileged: true # needed to allow shutdown
